#!/usr/bin/env node
/**
 * generate-config.js
 *
 * Reads Vercel environment variables and writes config.js into the project root.
 * Run automatically as part of the Vercel build step (`npm run build`).
 *
 * Required env vars (set in Vercel project dashboard):
 *   DRIFT_API_KEY         — Google Drive API key
 *   DRIFT_FOLDER_ID       — Google Drive folder ID
 *   GEMINI_KEY            — Google Gemini API key (AI Stories)
 *   SARVAM_KEY            — Primary Sarvam TTS key (Gujarati VIP)
 *   SARVAM_KEYS           — JSON array of rotation keys, e.g. '["sk_...","sk_..."]'
 *   ELEVEN_LABS_KEY       — ElevenLabs TTS key (English VIP, optional)
 *   ELEVEN_LABS_VOICE_ID  — ElevenLabs voice ID (default: Rachel)
 *
 * Local development: config.js is hand-written (gitignored) — this script is
 * NOT run locally unless you explicitly call `npm run build`.
 */

const fs = require('fs');
const path = require('path');

const outputPath = path.join(__dirname, '..', 'config.js');

// ── Auto-bump the service-worker cache version on every Vercel deploy ──
// sw.js is cache-first for shell assets; without a CACHE bump, returning web
// users keep stale app.js/styles.css forever. Stamp the version from the git
// SHA (or timestamp for CLI deploys) so every deploy invalidates the cache.
try {
  const swPath = path.join(__dirname, '..', 'sw.js');
  const stamp = (process.env.VERCEL_GIT_COMMIT_SHA || String(Date.now())).slice(0, 10);
  const sw = fs.readFileSync(swPath, 'utf8');
  const bumped = sw.replace(/const CACHE = 'sanskar-[^']+';/, `const CACHE = 'sanskar-${stamp}';`);
  if (bumped !== sw) {
    fs.writeFileSync(swPath, bumped);
    console.log(`[generate-config] sw.js CACHE stamped: sanskar-${stamp}`);
  }
} catch (e) {
  console.warn('[generate-config] sw.js stamp skipped:', e.message);
}

// Check that at least the required keys are present
const required = ['DRIFT_API_KEY', 'DRIFT_FOLDER_ID', 'GEMINI_KEY'];
const missing = required.filter((k) => !process.env[k]);

if (missing.length > 0) {
  // If config.js was already uploaded by the Vercel CLI (local deploy), keep it as-is.
  if (fs.existsSync(outputPath)) {
    console.log(
      `[generate-config] No env vars set — using existing config.js from deployment upload.`
    );
    process.exit(0);
  }
  // No env vars AND no uploaded config.js → fail clearly
  console.error(
    `[generate-config] ERROR: Missing required env vars: ${missing.join(', ')}\n` +
    `Set them in Vercel project dashboard → Settings → Environment Variables.`
  );
  process.exit(1);
}

// Parse sarvamKeys — stored as a JSON array string in the env var
let sarvamKeys = [];
try {
  sarvamKeys = JSON.parse(process.env.SARVAM_KEYS || '[]');
} catch {
  console.warn('[generate-config] WARNING: SARVAM_KEYS is not valid JSON, defaulting to empty array');
}

// If SARVAM_KEY is set but not in the rotation pool, prepend it
const primaryKey = process.env.SARVAM_KEY || '';
if (primaryKey && !sarvamKeys.includes(primaryKey)) {
  sarvamKeys = [primaryKey, ...sarvamKeys];
}

const config = {
  apiKey: process.env.DRIFT_API_KEY,
  folderId: process.env.DRIFT_FOLDER_ID,
  geminiKey: process.env.GEMINI_KEY,
  sarvamKey: primaryKey,
  sarvamKeys,
  elevenLabsKey: process.env.ELEVEN_LABS_KEY || '',
  elevenLabsVoiceId: process.env.ELEVEN_LABS_VOICE_ID || '21m00Tcm4TlvDq8ikWAM',
};

const content = `// config.js — AUTO-GENERATED by scripts/generate-config.js
// Do NOT edit manually. Set values via Vercel environment variables.
// Generated: ${new Date().toISOString()}

window.DRIFT_CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync(outputPath, content, 'utf8');
console.log(`[generate-config] ✓ config.js written (${content.length} bytes)`);
