#!/usr/bin/env node
/**
 * generate-config.js
 *
 * Reads Vercel environment variables and writes config.js into the project root.
 * Run automatically as part of the Vercel build step (`npm run build`).
 *
 * Required env vars (set in Vercel project dashboard):
 *   DRIFT_API_KEY         — Google Drive API key
 *   DRIFT_FOLDER_ID       — Google Drive folder ID
 *   GEMINI_KEY            — Google Gemini API key (AI Stories)
 *   SARVAM_KEY            — Primary Sarvam TTS key (Gujarati VIP)
 *   SARVAM_KEYS           — JSON array of rotation keys, e.g. '["sk_...","sk_..."]'
 *   ELEVEN_LABS_KEY       — ElevenLabs TTS key (English VIP, optional)
 *   ELEVEN_LABS_VOICE_ID  — ElevenLabs voice ID (default: Rachel)
 *
 * Local development: config.js is hand-written (gitignored) — this script is
 * NOT run locally unless you explicitly call `npm run build`.
 */

const fs = require('fs');
const path = require('path');

// Check that at least the required keys are present
const required = ['DRIFT_API_KEY', 'DRIFT_FOLDER_ID', 'GEMINI_KEY'];
const missing = required.filter((k) => !process.env[k]);

if (missing.length > 0) {
  console.error(
    `[generate-config] ERROR: Missing required environment variables: ${missing.join(', ')}\n` +
    `Set them in the Vercel project dashboard under Settings → Environment Variables.`
  );
  process.exit(1);
}

// Parse sarvamKeys — stored as a JSON array string in the env var
let sarvamKeys = [];
try {
  sarvamKeys = JSON.parse(process.env.SARVAM_KEYS || '[]');
} catch {
  console.warn('[generate-config] WARNING: SARVAM_KEYS is not valid JSON, defaulting to empty array');
}

// If SARVAM_KEY is set but not in the rotation pool, prepend it
const primaryKey = process.env.SARVAM_KEY || '';
if (primaryKey && !sarvamKeys.includes(primaryKey)) {
  sarvamKeys = [primaryKey, ...sarvamKeys];
}

const config = {
  apiKey: process.env.DRIFT_API_KEY,
  folderId: process.env.DRIFT_FOLDER_ID,
  geminiKey: process.env.GEMINI_KEY,
  sarvamKey: primaryKey,
  sarvamKeys,
  elevenLabsKey: process.env.ELEVEN_LABS_KEY || '',
  elevenLabsVoiceId: process.env.ELEVEN_LABS_VOICE_ID || '21m00Tcm4TlvDq8ikWAM',
};

const outputPath = path.join(__dirname, '..', 'config.js');

const content = `// config.js — AUTO-GENERATED by scripts/generate-config.js
// Do NOT edit manually. Set values via Vercel environment variables.
// Generated: ${new Date().toISOString()}

window.DRIFT_CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync(outputPath, content, 'utf8');
console.log(`[generate-config] ✓ config.js written (${content.length} bytes)`);
